package com.smartbooking.app.enums;

public enum IndustryType {
    SALON, DOCTOR_CLINIC, DENTAL_CLINIC, TUTORING, COOKING_CLASS, HOME_REPAIR,
    ELECTRICIAN, PLUMBING,
    MASSAGE_THERAPY,
    PET_GROOMING,
    CAR_SERVICING,
    YOGA_INSTRUCTOR,
    PHYSIOTHERAPY,
    MENTAL_HEALTH,
    CLEANING_SERVICE,
    EVENT_PLANNER,
    PHOTOGRAPHY,
    MUSIC_TEACHER,
    MAKEUP_ARTIST,
    CUSTOM
}